/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controlador.Metodos_libro;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Libros;

/**
 *
 * @author Usuario
 */
public class Modificar_libros extends javax.swing.JFrame {
    
     FondoPanel fondo =new FondoPanel();
    
    public static String nombre;
    public static boolean IoM;
    private DefaultTableModel dtm;
    Metodos_libro metl = new Metodos_libro();
    List<modelo.Libros> libro = null;
    /**
     * Creates new form Modificar_libros
     */
    public Modificar_libros() {
        
        this.setContentPane(fondo);
        
        initComponents();
        List<modelo.Libros> libro = metl.ListarLibro();
        dtm = (DefaultTableModel) tbl_lib.getModel();
        
        for (modelo.Libros li: libro) {
           Vector fila = new Vector();
//            fila.add(au.getId_autor());
            fila.add(li.getIcbn());
            fila.add(li.getNombre());
            fila.add(li.getNum_pag());
            fila.add(li.getEdicion());
            fila.add(li.getFecha());
            fila.add(li.getNom_edt());
            fila.add(li.getAutor_id());
            dtm.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lib = new javax.swing.JTable();
        btn_eliminarML = new javax.swing.JButton();
        btn_actualizarML = new javax.swing.JButton();
        btn_regresarML = new javax.swing.JButton();
        btn_salirML = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modificar LIbros");

        tbl_lib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ICBN", "Nombre", "Numero de Pag.", "Edicion", "Fecha publicacion", "Nombre editorial", "Aurtor ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_lib);

        btn_eliminarML.setText("Eliminar");
        btn_eliminarML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarMLActionPerformed(evt);
            }
        });

        btn_actualizarML.setText("Actualizar");
        btn_actualizarML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarMLActionPerformed(evt);
            }
        });

        btn_regresarML.setText("Regresar");
        btn_regresarML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarMLActionPerformed(evt);
            }
        });

        btn_salirML.setText("SALIR");
        btn_salirML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirMLActionPerformed(evt);
            }
        });

        btn_ingresar.setText("INGRESAR");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_actualizarML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_eliminarML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addComponent(btn_ingresar)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_regresarML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_salirML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_eliminarML)
                            .addComponent(btn_regresarML))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_actualizarML)
                            .addComponent(btn_salirML))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ingresar)
                        .addGap(74, 74, 74))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarMLActionPerformed
Menu me=new Menu();
  me.setVisible(true);
  this.setVisible(false);

    }//GEN-LAST:event_btn_regresarMLActionPerformed

    private void btn_salirMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirMLActionPerformed
this.dispose();
    }//GEN-LAST:event_btn_salirMLActionPerformed

    private void btn_actualizarMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarMLActionPerformed
        int filaSeleccionada = tbl_lib.getSelectedRow();
        if (filaSeleccionada >= 0) {
             dtm = (DefaultTableModel) tbl_lib.getModel();
             nombre = (String) dtm.getValueAt(filaSeleccionada, 1);
             IoM=true;
             Agregar_libros mc = new Agregar_libros();
             mc.setVisible(true);
             this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione la fila a modificar");
        }        
    }//GEN-LAST:event_btn_actualizarMLActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
            IoM=false;
             Agregar_libros mc = new Agregar_libros();
             mc.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_eliminarMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarMLActionPerformed
        
        int filaSeleccionada = tbl_lib.getSelectedRow();
        if (filaSeleccionada >= 0) {
             dtm = (DefaultTableModel) tbl_lib.getModel();
             nombre = (String) dtm.getValueAt(filaSeleccionada, 1);
             if(!nombre.trim().equals("")
                && JOptionPane.showConfirmDialog(this, "Seguro que desea Eliminar",
                        "Ingreso Cliente", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE)==0){
             metl.eliminarRegistro(nombre);
             eliminar();
             libro = metl.ListarLibro();
             cargarTabla(libro);
        }
        
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione elemento a eliminar");
        }
        
    }//GEN-LAST:event_btn_eliminarMLActionPerformed

    public void eliminar(){ 
     try{
        DefaultTableModel dtm = (DefaultTableModel) tbl_lib.getModel();
        int a = tbl_lib.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        dtm.removeRow(dtm.getRowCount()-1);
        } 
     }catch(Exception ex){
         System.out.println("Error al limpiar tabla");
     }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarML;
    private javax.swing.JButton btn_eliminarML;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_regresarML;
    private javax.swing.JButton btn_salirML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_lib;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(List<Libros> libro) {
       dtm = (DefaultTableModel) tbl_lib.getModel();
        
        for (modelo.Libros li: libro) {
           Vector fila = new Vector();
//            fila.add(au.getId_autor());
            fila.add(li.getIcbn());
            fila.add(li.getNombre());
            fila.add(li.getNum_pag());
            fila.add(li.getEdicion());
            fila.add(li.getFecha());
            fila.add(li.getNom_edt());
            fila.add(li.getAutor_id());
            dtm.addRow(fila);
        }
    }
    
    
    class FondoPanel extends JPanel{
        private Image imagen ;
        
        
        @Override
        public void paint(Graphics g){
            
            imagen = new ImageIcon(getClass().getResource("/imagenes/3.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0,getWidth(), getHeight(), this );
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
    
}
